name: Elasticsearch, Logstash, Kibana (ELK)
description: provides a convenient centralised log server and log management web interface, by packaging Elasticsearch, Logstash, and Kibana, collectively known as ELK.
category: Analytics
version: 1